name: shell commands
on: push
jobs:
    run-shell-commands:
        runs-on: ubunto-latest
        steps:
        - name: echo a string
          run: echo "hello world"
        - name: multiline scripts
          run: |
            node -v
            npm -v

        
